create table if not exists public.sam_contact_requests (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(255) not null,
  phone varchar(20),
  messages text not null,
  created_at timestamptz not null default now()
);

alter table public.sam_contact_requests enable row level security;

grant insert on table public.sam_contact_requests to anon, authenticated;

drop policy if exists "Anyone can submit contact requests" on public.sam_contact_requests;
create policy "Anyone can submit contact requests"
on public.sam_contact_requests
for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 120
  and char_length(email) between 3 and 320
  and char_length(messages) between 1 and 5000
  and (phone is null or char_length(phone) <= 40)
);
